baseURL = "https://kidscancode.org/godot_recipes/"
publishDir = "../docs"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Godot Recipes"
theme = "hugo-theme-learn-cb"
pygmentsStyle = "dracula"
pygmentsCodeFences = true
googleAnalytics = "UA-39851424-1"
disqusShortname = "kidscancode"

[params]
	disableNextPrev = true
	themeVariant = "green"
	disableInlineCopyToClipBoard = true
	disableAssetsBusting = false
	disableShortcutsTitle = true
	disableLandingPageButton = true
	ordersectionsby = "weight"

[outputs]
	home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
	unsafe = true

[minify]
  minifyOutput = false

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true

[[menu.shortcuts]]
    name = "<i class='fas fa-tags'></i>&nbsp;Tags"
    url = "/tags"
    weight = 30

[Languages]
    [Languages.en]
        title = "Godot Recipes"
        weight = 1
        languageName = "English"

    [Languages.ru]
        title = "Рецепты Godot"
        weight = 2
        languageName = "Русский"
    [[Languages.ru.menu.shortcuts]]
        name = "<i class='fas fa-tags'></i>&nbsp;Теги"
        url = "/tags"
        weight = 30